# CONFIGURE GAME OPTIONS, MUST MATCH WITH SERVER
#XSIZE = 5
#YSIZE = 5
#MAX_COLOR = 4

# DO NOT TOUCH UNLESS YOU KNOW WHAT YOU'RE DOING
COLOR_MAPPING = ['Blue','Yellow','Red','Green']
NONE = 0
TREE = 1
PALM = 2
GRAVE = 3
TOWER = 4
CITY = 5
MAN = 6
SPEARMAN = 7
KNIGHT = 8
BARON = 9